### ISSUE TITLE
Dokka 1.9.x Support

### ISSUE THREAD

**Issue by tedberg** [glureau/dokka-mermaid#4]
Dokka 1.9.0 made some breaking changes, shown in their release notes.  Under that version, this plugin now fails to render diagrams.  It only gives an error in the console "TypeError: undefined is not an object (evaluating 'a.createElementNS')".

**Comment by glureau** [comment]
Thanks for the report, I finally found the time.
1.9.10 is supported with https://github.com/glureau/dokka-mermaid/releases/tag/0.6.0

Tell me if you notice something wrong, I only made very basic tests.
