### ISSUE TITLE
Link to Mermaid.js is wrong when using it with Package Readme.md

### ISSUE THREAD

**Issue by hfhbd** [glureau/dokka-mermaid#7]
I put a mermaid diagram in the package level declaration of the readme:
````
# Package com.example

Foo

```mermaid
graph LR
  Foo
```
````

Dokka generates this html: `html/com.example/index.html` but the link to `dokka-mermaid.js` is `../../dokka-mermaid.js` but should be `../dokka-mermaid.js` because the file is stored in `html/dokka-mermaid.js`.

**Comment by hfhbd** [comment]
Maybe it is a bug in Dokka, I didn't find a path relevant code in this plugin, will create another ticket in dokka.

**Comment by hfhbd** [comment]
I use multi modules, so I fixed this issue with adding the plugin to the root project too. I still think, Dokka should update its resource logic.

**Comment by glureau** [comment]
Thank you for the feedback and for next developers having the same problem. Have a nice day!
